## Pandas Series Basics

In [2]:
import pandas as pd

marks = pd.Series([78, 85, 90, 66, 72])

In [3]:
marks

0    78
1    85
2    90
3    66
4    72
dtype: int64

In [4]:
print("Series values:", marks.values)
print("Index:", marks.index)
print("Data type:", marks.dtype)

Series values: [78 85 90 66 72]
Index: RangeIndex(start=0, stop=5, step=1)
Data type: int64

In [5]:
print("First element:", marks.iloc[0])
print("Last two elements:")
print(marks.iloc[-2:])

First element: 78
Last two elements:
3    66
4    72
dtype: int64

## Task 2: Mathematical Operations on Series

In [3]:
import pandas as pd

In [4]:

marks = pd.Series([78, 85, 90, 66, 72])

In [5]:
grace_marks = marks + 5
print("After adding 5 grace marks:")
print(grace_marks)

After adding 5 grace marks:
0    83
1    90
2    95
3    71
4    77
dtype: int64

In [6]:
subtracted = marks - 2
print("After subtracting 2 marks:")
print(subtracted)

After subtracting 2 marks:
0    76
1    83
2    88
3    64
4    70
dtype: int64

In [7]:
multiplied = marks * 1.05
print("After multiplying by 1.05:")
print(multiplied)

After multiplying by 1.05:
0    81.90
1    89.25
2    94.50
3    69.30
4    75.60
dtype: float64

In [8]:
divided = marks / 2
print("After dividing by 2:")
print(divided)

After dividing by 2:
0    39.0
1    42.5
2    45.0
3    33.0
4    36.0
dtype: float64

## Task 3: Python Functionalities on Series

In [9]:
print("Maximum marks:", marks.max())
print("Minimum marks:", marks.min())
print("Sum of marks:", marks.sum())
print("Mean marks:", marks.mean())

Maximum marks: 90
Minimum marks: 66
Sum of marks: 391
Mean marks: 78.2

In [10]:
passed_status = marks.apply(lambda x: x >= 70)
print("Pass status for each student:")
print(passed_status)

Pass status for each student:
0     True
1     True
2     True
3    False
4     True
dtype: bool

In [11]:
num_passed = passed_status.sum()
print("Number of students who passed:", num_passed)

Number of students who passed: 4

In [13]:
num_passed = passed_status.sum()
print("Number of students who passed:", num_passed)

Number of students who passed: 4

In [12]:
students = {
    'Name': ['Amit', 'Neha', 'Rahul', 'Sneha', 'Pooja'],
    'Marks': [78, 85, 90, 66, 72],
    'Subject': ['Math', 'Math', 'Science', 'Science', 'Math']
}

df = pd.DataFrame(students)
df

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [14]:
print("First 3 rows:")
df.head(3)

First 3 rows:

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science

In [16]:
print("Last 2 rows:")
df.tail(2)

Last 2 rows:

    Name  Marks  Subject
3  Sneha     66  Science
4  Pooja     72     Math

In [17]:

print("DataFrame shape:", df.shape)
print("Column names:", df.columns.tolist())

DataFrame shape: (5, 3)
Column names: ['Name', 'Marks', 'Subject']

## Task 5: Important DataFrame Functions

In [18]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      str
 1   Marks    5 non-null      int64
 2   Subject  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 301.0 bytes

           Marks
count   5.000000
mean   78.200000
std     9.654015
min    66.000000
25%    72.000000
50%    78.000000
75%    85.000000
max    90.000000

In [19]:
df.head()

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [20]:
df.tail()

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [21]:
df_sorted = df.sort_values(by='Marks', ascending=False)
print("Students sorted by Marks (descending):")
df_sorted

Students sorted by Marks (descending):

    Name  Marks  Subject
2  Rahul     90  Science
1   Neha     85     Math
0   Amit     78     Math
4  Pooja     72     Math
3  Sneha     66  Science

In [22]:
df_sorted_reset = df_sorted.reset_index(drop=True)
print("After resetting index:")
df_sorted_reset

After resetting index:

    Name  Marks  Subject
0  Rahul     90  Science
1   Neha     85     Math
2   Amit     78     Math
3  Pooja     72     Math
4  Sneha     66  Science

## Task 6: Filtering & Conditional Selection

In [23]:
above_75 = df[df['Marks'] > 75]
print("Students who scored more than 75 marks:")
above_75

Students who scored more than 75 marks:

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science

In [24]:
math_students = df[df['Subject'] == 'Math']
print("Students belonging to Math:")
math_students

Students belonging to Math:

    Name  Marks Subject
0   Amit     78    Math
1   Neha     85    Math
4  Pooja     72    Math

In [25]:
above_average = df[df['Marks'] > df['Marks'].mean()]
print("Students who scored more than average marks:")
above_average

Students who scored more than average marks:

    Name  Marks  Subject
1   Neha     85     Math
2  Rahul     90  Science

In [26]:
failed_students = df[df['Marks'] < 70]
print("Students who failed (marks < 70):")
failed_students

Students who failed (marks < 70):

    Name  Marks  Subject
3  Sneha     66  Science

## Task 7: Grouping & Basic Analysis

In [27]:
avg_marks_per_subject = df.groupby('Subject')['Marks'].mean()
print("Average marks per subject:")
avg_marks_per_subject

Average marks per subject:

Subject
Math       78.333333
Science    78.000000
Name: Marks, dtype: float64

In [28]:
students_per_subject = df.groupby('Subject')['Marks'].count()
print("Number of students per subject:")
students_per_subject

Number of students per subject:

Subject
Math       3
Science    2
Name: Marks, dtype: int64

In [29]:
max_marks_per_subject = df.groupby('Subject')['Marks'].max()
print("Maximum marks per subject:")
max_marks_per_subject

Maximum marks per subject:

Subject
Math       85
Science    90
Name: Marks, dtype: int64

## Task 8: Pandas Plotting (Simple Graphs)

In [30]:


Using only `DataFrame.plot()` / `Series.plot()`, no matplotlib customization.

SyntaxError: invalid syntax (2328899978.py, line 1)

In [32]:
df.plot(x='Name', y='Marks', kind='bar', title='Student Names vs Marks', legend=False)

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

## Task 9: Mini Use Case - Sales Data Analysis

In [33]:
sales = {
    'Day': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    'Revenue': [1200, 1500, 900, 2000, 1800]
}

sales_df = pd.DataFrame(sales)
sales_df

   Day  Revenue
0  Mon     1200
1  Tue     1500
2  Wed      900
3  Thu     2000
4  Fri     1800

In [34]:
total_revenue = sales_df['Revenue'].sum()
print("Total revenue:", total_revenue)

Total revenue: 7400

In [35]:
average_revenue = sales_df['Revenue'].mean()
print("Average daily revenue:", average_revenue)

Average daily revenue: 1480.0

In [36]:
highest_day = sales_df.loc[sales_df['Revenue'].idxmax(), 'Day']
print("Day with highest revenue:", highest_day)

Day with highest revenue: Thu

In [37]:
above_avg_days = sales_df[sales_df['Revenue'] > average_revenue]
print("Days where revenue is above average:")
above_avg_days

Days where revenue is above average:

   Day  Revenue
1  Tue     1500
3  Thu     2000
4  Fri     1800

In [38]:
sales_df.plot(x='Day', y='Revenue', kind='bar', title='Revenue vs Day', legend=False)

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.