## sum()

import pandas as pd

In [1]:
import pandas as pd

In [6]:
data=pd.read_csv("youtube-videos.csv")

In [7]:
data

,rank,Video,Video views,Likes,Dislikes,Category,published
0,1,"20 Tennis shots if they were not filmed, NOBOD...","3,471,237","19,023",859,NaN,2017
1,2,Lil Nas X - Old Town Road (Official Movie) ft....,"54,071,677","3,497,955","78,799",Music,2019
2,3,JoJo Siwa - Karma (Official Video),"34,206,747","293,563",NaN,Music,2024
3,4,Wiz Khalifa - See You Again ft. Charlie Puth [...,"6,643,904,918","44,861,602",NaN,Music,2015
4,5,伊賀の天然水強炭酸水「家族で、シュワシェア。」篇 15秒,"236,085,971",38,NaN,NaN,2021
...,...,...,...,...,...,...,...
995,996,CALIFORNIA - MONDAY JUSTICE FEAT. SNOOP DOGG (...,"943,248","2,949",22,Music,2017
996,997,John McEnroe's most famous outburst happened i...,"4,853,621","7,254",426,Sports,2010
997,998,Adi Golan's Group - Teaser,"56,578",NaN,NaN,Music,2014
998,999,Keg tapping goes horribly wrong.,"751,804","3,427",313,Entertainment,2017
999,1000,LIVE Hurricane Irma - Downtown Orlando - Ameri...,"554,438",184,8,News & Politics,2016

In [11]:
subs=data['Video views']

In [12]:
subs

0          3,471,237
1         54,071,677
2         34,206,747
3      6,643,904,918
4        236,085,971
           ...
995          943,248
996        4,853,621
997           56,578
998          751,804
999          554,438
Name: Video views, Length: 1000, dtype: str

In [13]:
subs.sum()

'3,471,23754,071,67734,206,7476,643,904,918236,085,97176,834,49518,558,39096,6869,605,9698,353,3188,718,3267,396,1997,958,18114,612,15313,894,90537,460,2968,286,09613,764,0986,953,8388,414,6765,851,41110,627,79798,468,5368,322,488699,38211,638,2015,756,53511,894,0765,923,0171,097,393,69559,857,48955,113,25316,676,5604,386,5643,845,18628,181,2416,484,6223,873,12115,694,3175,272,4872,993,030,4995,856,94612,643,8417,010,73220,146,9245,353,676514,69421,786,7323,409,9063,102,7517,529,9273,777,9972,985,3005,038,8485,461,43239,407,67417,802,7478,066,4218,690,90010,748,28616,485,6062,692,74021,596,6233,305,68136,311,87513,591,2499,857,163204,78252,049,7054,669,5462,943,1591,018,7135,250,4586,040,4295,989,0585,938,41614,921,4374,929,4813,630,53417,275,25010,188,5902,663,55081,744,4579,884,00512,255,4562,960,4938,393,2452,279,8336,016,6572,113,438148,996,97617,166,1296,587,4476,354,77168,224,9794,645,8154,485,52932,387,91810,779,0323,870,4512,638,35613,933,73561,892,7924,702,8702,472,0453,590,24812,649,3333,954,3022,714,14024,340,65222,029,1003,824,0532,032,4865,352,7512,754,5182,003,2217,352,6242,894,7003,086,6673,416,6954,385,1023,829,0954,196,3001,847,58016,040,6492,224,022,7983,415,7005,806,5222,126,9303,763,8942,691,3322,420,71925,671,5633,725,1612,596,72520,502,04523,778,4131,556,3472,345,41537,787,0552,451,2021,888,3884,399,6932,136,2083,293,5943,360,2622,540,0792,368,5874,406,4673,391,88112,935,16750,822,03625,576,3826,189,11030,475,5183,751,7232,195,08121,492,93213,257,4013,818,2601,699,5882,866,1095,198,7252,683,8562,600,4802,181,1602,194,6402,257,4601,677,73310,500,0736,849,5962,443,71327,215,1839,140,9941,422,3422,126,6742,337,8881,645,37721,061,22320,688,8702,173,3961,338,4413,400,8505,289,5913,476,63513,893,5272,760,3031,592,22514,399,34821,865,90283,720,4747,927,77410,363,3161,662,97411,757,6391,581,46322,225,3993,128,36711,474,1297,095,2441,605,5586,691,2132,126,0102,285,4481,765,3155,337,3812,138,1366,705,3963,923,8929,071,1391,895,7741,352,1401,450,0056,459,7875,767,74412,559,12872,815,2443,264,0261,776,4772,641,3331,494,1412,021,81716,093,1341,330,3631,226,13835,610,82745,597,95124,082,6313,212,9367,261,71012,093,7133,062,4484,827,0886,636,0773,012,7753,510,3452,002,4912,068,5324,245,3902,751,7754,525,9357,980,1992,124,4291,275,9121,370,1004,148,0131,320,9292,601,3924,119,4051,886,65111,658,9714,422,0052,716,31891,527,89410,671,7142,531,88112,348,4071,949,4565,192,6503,079,2342,934,5851,415,0451,143,3341,486,82422,529,1786,815,5053,653,6023,649,04422,504,8022,566,3132,516,6724,851,0711,020,6043,393,6001,283,5502,171,4351,388,3272,637,02422,620,7095,099,1011,070,7671,421,6521,207,2171,394,3721,851,6812,659,1501,232,7893,569,4732,142,7311,998,8581,459,76613,021,0629,735,0981,669,27222,075,5231,310,7031,642,52915,504,92134,955,9011,194,1498,915,2028,170,8181,787,1693,795,1641,891,70730,170,0144,208,0598,114,37615,985,7351,144,9411,688,4539,605,3234,782,4165,766,75145,990,4111,614,63217,485,0161,130,1411,845,5053,952,85117,363,8462,399,769,75711,622,7271,625,194346,4863,997,76914,813,63345,105,96315,766,8897,005,95113,524,9752,134,9914,916,0421,891,7103,036,4513,040,3982,110,2534,292,4718,191,516962,4371,921,7033,432,7911,804,5893,379,0648,162,9693,670,4911,040,965788,3252,067,2444,000,76910,358,6631,281,7213,474,3341,698,42348,637,7467,022,7461,634,6841,428,3282,271,5922,576,1291,190,3562,900,7192,394,2522,058,0823,411,9902,482,3091,132,3904,321,63440,116,402101,094,61231,499,047156,690,6861,024,8551,072,3693,324,459982,7301,140,6571,041,8963,050,76412,466,4311,123,5201,237,5861,576,9423,875,0111,731,3222,061,29017,056,4002,730,3361,009,2821,227,8448,411,1337,852,0435,081,9154,592,08022,426,928885,7063,320,8571,263,6513,975,1911,586,5503,957,2393,824,6931,512,5633,502,7971,574,5641,407,3967,812,8569,619,5419,149,6071,135,4062,379,8861,439,8143,351,8125,260,8341,736,9014,970,8411,818,3263,334,3482,141,164974,5193,320,3669,700,0068,058,3643,488,8202,144,7101,417,6553,285,2841,397,6585,615,5453,672,8876,005,45711,170,71434,772,21116,651,5071,551,8252,246,35615,489,6132,218,6101,068,6982,028,2116,903,203914,1681,593,7871,830,212885,313983,9191,574,14978,178,105888,8933,580,228322,4893,694,1025,498,42238,507,85948,695,61318,423,43732,695,89637,544,6689,558,07212,552,9484,043,3211,208,7502,264,72838,332,23918,308,842280,745,87237,730,4643,474,9042,358,6581,080,2961,867,4691,743,4371,941,2052,807,0491,530,7791,320,2191,894,1101,465,5452,081,718896,4644,758,1921,596,4471,227,17626,882,2291,315,9771,144,2114,833,7883,121,5971,083,0361,903,81514,941,18520,096,070809,3892,429,7744,668,1205,666,5519,550,4731,701,3404,546,88010,537,3171,352,408944,46111,940,1341,694,1854,245,7574,816,6241,532,1082,306,1901,216,0901,142,6793,775,9803,458,7312,362,8605,943,7025,529,7985,400,7446,380,1821,803,1205,370,442635,3951,155,7081,735,46424,914,13834,686,08511,370,9338,058,1187,149,5561,212,6991,606,5693,798,2866,332,5401,366,2751,291,92658,296,7851,205,7331,889,5712,157,1971,077,182146,925,966133,062,446749,03660,535,0692,139,2321,588,9985,368,5324,822,6701,668,6865,396,154117,001,584765,4233,139,9019,822,8932,441,7303,126,7432,838,7512,375,6821,880,0221,301,2762,104,40854,003,55713,848,8135,644,916437,840969,2713,102,7461,694,23521,752,141908,62630,976,7628,029,18635,496,2347,045,2491,595,3883,964,7623,541,0356,683,0012,783,9941,103,3241,220,2511,098,0054,875,2391,260,1333,293,3651,194,6322,668,2689,868,6743,006,0305,002,420836,1841,552,4777,527,1251,274,520769,783847,249711,3531,998,307885,1491,154,3762,812,9941,568,9033,640,9581,301,1652,298,70915,505,9943,583,270720,4375,634,6533,586,169896,4195,842,7281,200,3851,606,95514,378,5531,047,2812,166,7921,136,2351,212,2531,060,0483,714,2312,581,13710,288,0901,337,402861,15344,730,8241,597,7391,223,6752,595,0291,006,8601,069,15373,698,5622,125,1871,613,8181,463,580877,6511,610,253820,548899,5201,538,8561,001,6059,347,4511,240,2201,128,9473,120,409940,489951,835757,7181,054,5051,015,509726,8261,019,64119,956,5333,023,95816,762,38831,909,7653,085,8693,137,4854,273,1762,030,8241,167,5993,355,4793,464,45013,870,4675,092,95747,154,37933,353,3872,581,5812,700,43176,133,77467,630,8004,678,07181,323,847141,469,07469,350,734685,1898,730,4891,099,456676,9861,590,7096,299,70538,076,7621,451,2351,684,7441,159,2141,344,7702,218,5722,740,1111,135,5132,048,7732,023,8161,282,361510,985825,8291,944,899999,009874,3651,163,8001,623,50632,829,3852,789,60912,939,9601,012,8661,312,023743,942995,595651,4369,248,421896,05948,947,99810,235,02562,614,1858,393,8713,492,6943,102,872601,433957,498710,8502,819,8801,628,50154,091,01818,376,22118,846,951682,9411,984,7501,257,6211,509,5261,089,0841,017,7382,083,0692,109,4471,034,276868,433545,044715,609672,9772,756,6272,594,516622,7823,658,7991,342,1691,125,1942,389,729980,4412,098,8441,379,9551,591,6322,786,159818,670726,2932,049,699734,558498,9411,650,882853,961661,841205,257858,6971,883,57030,153,9712,699,9043,326,126512,9911,132,9721,410,35512,521,35822,829,976641,2488,558,3012,424,328661,8531,950,860730,4942,420,7832,185,2662,353,69614,025,6121,379,49710,876,9852,602,20425,349,9772,592,135720,7392,389,276742,4984,040,4972,911,0921,053,8126,012,4039,844,0021,151,2111,318,16314,240,3391,533,9713,570,1997,560,798757,81710,269,7741,132,3621,370,0462,144,22932,808,0963,675,4885,154,149693,5028,846,66713,329,84317,642,7981,274,6971,193,7702,908,526650,6991,206,374951,6922,082,3291,051,4062,110,5771,475,6341,015,2481,567,73812,100,8101,198,9161,045,8714,352,9521,528,271701,3083,865,9784,117,2281,736,200601,9931,898,5641,063,45638,509,445729,06820,177,6112,396,0851,934,789865,86777,123,4697,829,229928,250852,3253,443,90110,514,30314,018,3132,605,0841,891,7691,095,01173,165,51710,642,4417,090,7834,941,173865,0653,304,460869,3182,594,43132,562,8513,822,060680,6296,232,7921,404,690712,0721,963,3362,568,713705,58169,659,0131,058,1181,701,7001,437,1271,479,394728,763774,4309,056,254635,00214,234,3929,598,4111,347,60525,610,1968,254,12817,367,547692,7702,772,3785,175,2992,083,9231,957,3953,583,26413,378,1021,191,811758,11314,265,0641,405,6184,890,361700,921739,52722,449,0348,075,76522,454,152832,845769,6381,727,971702,178903,229814,48227,166,456830,5665,460,1891,822,0838,226,0819,658,124583,139952,4521,356,7811,783,3731,535,7321,434,9992,381,406987,2652,762,811124,380,183592,93086,474,636686,7472,945,78126,339,2051,036,6723,682,2231,872,6371,655,9641,122,7381,635,9741,706,353545,5741,864,0492,051,016671,2911,142,028556,376646,8321,529,281766,3641,348,3692,630,9314,440,3361,748,740943,3851,275,336681,62418,428,30745,622,9648,680,50145,632,3265,114,8184,044,462731,822670,7993,469,1603,690,43657,324,296737,4046,502,2612,766,4731,249,8013,702,69610,945,6621,884,8341,654,9601,614,42910,615,3802,371,99327,566,20221,193,17223,465,0841,908,813805,8652,056,24321,679,2235,790,9397,540,23118,742,99456,145,6731,133,562835,9477,594,4847,135,78514,316,983902,1132,271,314979,231815,205502,2453,472,4492,986,9141,263,0443,975,0371,273,971706,418498,038943,2484,853,62156,578751,804554,438'

In [15]:
subs.sort_values()

638    1,001,605
627    1,006,860
388    1,009,282
700    1,012,866
816    1,015,248
         ...
375      982,730
445      983,919
914      987,265
703      995,595
693      999,009
Name: Video views, Length: 1000, dtype: str

In [18]:
print(subs.head())
print(subs.dtype)

0        3,471,237
1       54,071,677
2       34,206,747
3    6,643,904,918
4      236,085,971
Name: Video views, dtype: str
str

In [21]:
subs.mean()

nan

In [22]:
subs.median()

np.float64(nan)

In [23]:
subs.mode()

Series([], Name: Video views, dtype: float64)

In [24]:
subs=data['Likes']

In [25]:
subs

0          19,023
1       3,497,955
2         293,563
3      44,861,602
4              38
          ...
995         2,949
996         7,254
997           NaN
998         3,427
999           184
Name: Likes, Length: 1000, dtype: str

In [28]:
subs=pd.to_numeric(subs,errors="coerce")

In [30]:
print(subs.dtype)

float64

In [31]:
subs.mean()

np.float64(227.03061224489795)

In [32]:
subs.sum()

np.float64(66747.0)

In [33]:
subs.median()

np.float64(45.0)

In [35]:
subs.mode()

0    2.0
Name: Likes, dtype: float64

In [37]:
subs.describe()

count    294.000000
mean     227.030612
std      296.347704
min        0.000000
25%        8.000000
50%       45.000000
75%      399.500000
max      996.000000
Name: Likes, dtype: float64

In [38]:
subs.std()

np.float64(296.34770374853593)

In [40]:
subs.var()

np.float64(87821.96151703001)

In [41]:
subs.max()

np.float64(996.0)

In [42]:
subs.min()

np.float64(0.0)

## Indexing in Series

In [43]:
subs[2:12:2]

2      NaN
4     38.0
6      NaN
8      6.0
10    46.0
Name: Likes, dtype: float64

In [45]:
subs[::-1]

999    184.0
998      NaN
997      NaN
996      NaN
995      NaN
       ...
4       38.0
3        NaN
2        NaN
1        NaN
0        NaN
Name: Likes, Length: 1000, dtype: float64

In [4]:
import pandas as pd

In [8]:
data=pd.read_csv("Libraries/Pandas/Student_Depression_Dataset.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Libraries/Pandas/Student_Depression_Dataset.csv'

In [14]:
data = pd.read_csv(r"C:/GenAI/Libraries/Pandas/Student_Depression_Dataset.csv")

In [15]:
data

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

## filtiring

In [16]:
data.head(3)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0

In [19]:
data[data['Financial Stress']==5]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
14,103,Female,19.0,Kalyan,Student,5.0,0.0,5.64,5.0,0.0,Less than 5 hours,Moderate,Class 12,Yes,4.0,5.0,Yes,1
16,120,Male,25.0,Nashik,Student,5.0,0.0,6.51,2.0,0.0,Less than 5 hours,Unhealthy,M.Ed,Yes,2.0,5.0,Yes,1
22,166,Female,25.0,Ahmedabad,Student,3.0,0.0,5.57,3.0,0.0,More than 8 hours,Unhealthy,MSc,Yes,10.0,5.0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27869,140512,Male,30.0,Hyderabad,Student,5.0,0.0,9.71,2.0,0.0,7-8 hours,Unhealthy,M.Ed,Yes,9.0,5.0,No,1
27874,140530,Female,19.0,Ghaziabad,Student,3.0,0.0,9.93,3.0,0.0,7-8 hours,Unhealthy,Class 12,Yes,4.0,5.0,No,1
27883,140584,Female,22.0,Kanpur,Student,4.0,0.0,6.61,2.0,0.0,More than 8 hours,Unhealthy,M.Com,Yes,6.0,5.0,No,1
27891,140645,Female,28.0,Thane,Student,4.0,0.0,7.77,3.0,0.0,Less than 5 hours,Unhealthy,MSc,No,2.0,5.0,No,1
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1

In [18]:
data.dtypes

id                                         int64
Gender                                       str
Age                                      float64
City                                         str
Profession                                   str
Academic Pressure                        float64
Work Pressure                            float64
CGPA                                     float64
Study Satisfaction                       float64
Job Satisfaction                         float64
Sleep Duration                               str
Dietary Habits                               str
Degree                                       str
Have you ever had suicidal thoughts ?        str
Work/Study Hours                         float64
Financial Stress                         float64
Family History of Mental Illness             str
Depression                                 int64
dtype: object

In [20]:
data.head(5)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

In [22]:
data['Age'].value_counts()

Age
24.0    2258
20.0    2237
28.0    2133
29.0    1950
33.0    1893
25.0    1784
21.0    1726
23.0    1645
18.0    1587
19.0    1560
34.0    1468
27.0    1462
31.0    1427
32.0    1262
22.0    1160
26.0    1155
30.0    1145
35.0      10
38.0       8
36.0       7
42.0       4
39.0       3
48.0       3
43.0       2
46.0       2
37.0       2
58.0       1
49.0       1
51.0       1
44.0       1
59.0       1
54.0       1
56.0       1
41.0       1
Name: count, dtype: int64

In [23]:
data['City'].value_counts()

City
Kalyan                1570
Srinagar              1372
Hyderabad             1340
Vasai-Virar           1290
Lucknow               1155
Thane                 1139
Ludhiana              1111
Agra                  1094
Surat                 1078
Kolkata               1066
Jaipur                1036
Patna                 1007
Visakhapatnam          969
Pune                   968
Ahmedabad              951
Bhopal                 934
Chennai                885
Meerut                 825
Rajkot                 816
Delhi                  768
Bangalore              767
Ghaziabad              745
Mumbai                 699
Vadodara               694
Varanasi               685
Nagpur                 651
Indore                 643
Kanpur                 609
Nashik                 547
Faridabad              461
Saanvi                   2
Bhavna                   2
City                     2
Harsha                   2
M.Tech                   1
Less Delhi               1
3.0                      1
Less than 5 Kalyan       1
Mira                     1
Vaanya                   1
Gaurav                   1
Harsh                    1
Reyansh                  1
Kibara                   1
Rashi                    1
ME                       1
M.Com                    1
Nalyan                   1
Mihir                    1
Nalini                   1
Nandini                  1
Khaziabad                1
Name: count, dtype: int64

In [24]:
data['Gender'].value_counts()

Gender
Male      15547
Female    12354
Name: count, dtype: int64

In [26]:
data['Academic Pressure'].value_counts()

Academic Pressure
3.0    7462
5.0    6296
4.0    5155
1.0    4801
2.0    4178
0.0       9
Name: count, dtype: int64

In [27]:
data['Sleep Duration'].value_counts()

Sleep Duration
Less than 5 hours    8310
7-8 hours            7346
5-6 hours            6183
More than 8 hours    6044
Others                 18
Name: count, dtype: int64

In [28]:
data['Profession'].value_counts()

Profession
Student                   27870
Architect                     8
Teacher                       6
Digital Marketer              3
Content Writer                2
Chef                          2
Doctor                        2
Pharmacist                    2
Civil Engineer                1
UX/UI Designer                1
Educational Consultant        1
Manager                       1
Lawyer                        1
Entrepreneur                  1
Name: count, dtype: int64

In [29]:
data.dtypes

id                                         int64
Gender                                       str
Age                                      float64
City                                         str
Profession                                   str
Academic Pressure                        float64
Work Pressure                            float64
CGPA                                     float64
Study Satisfaction                       float64
Job Satisfaction                         float64
Sleep Duration                               str
Dietary Habits                               str
Degree                                       str
Have you ever had suicidal thoughts ?        str
Work/Study Hours                         float64
Financial Stress                         float64
Family History of Mental Illness             str
Depression                                 int64
dtype: object

In [30]:
data[(data['Profession']=='Teacher') & (data['Depression']==1)]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
3841,19226,Male,31.0,Rajkot,Teacher,3.0,0.0,7.48,5.0,0.0,5-6 hours,Unhealthy,MD,Yes,12.0,2.0,Yes,1
5016,25193,Male,24.0,Kalyan,Teacher,4.0,0.0,9.66,5.0,0.0,7-8 hours,Moderate,BE,Yes,12.0,3.0,No,1
24121,121474,Male,27.0,Kalyan,Teacher,3.0,0.0,5.89,3.0,0.0,Less than 5 hours,Unhealthy,MSc,Yes,2.0,5.0,No,1
24482,123259,Male,23.0,Kanpur,Teacher,3.0,0.0,5.59,1.0,0.0,More than 8 hours,Healthy,BCA,Yes,11.0,4.0,Yes,1
26289,132550,Male,25.0,Visakhapatnam,Teacher,5.0,0.0,7.25,1.0,0.0,7-8 hours,Unhealthy,B.Ed,Yes,1.0,1.0,Yes,1

In [33]:
data[(data['Profession']=='Student') & (data['Age']==23) & (data['City']=='Pune') & (data['Gender']=='Male') & (data['Sleep Duration']=='5-6 hours') & (data['Degree']=='B.Tech')]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
4959,24869,Male,23.0,Pune,Student,3.0,0.0,5.77,4.0,0.0,5-6 hours,Moderate,B.Tech,Yes,12.0,1.0,Yes,1
19474,98661,Male,23.0,Pune,Student,3.0,0.0,9.21,5.0,0.0,5-6 hours,Unhealthy,B.Tech,Yes,0.0,5.0,No,1
25965,130855,Male,23.0,Pune,Student,4.0,0.0,6.16,3.0,0.0,5-6 hours,Unhealthy,B.Tech,Yes,4.0,5.0,Yes,1

In [34]:
data.shape

(27901, 18)

In [35]:
data['Sleep Duration'].value_counts()

Sleep Duration
Less than 5 hours    8310
7-8 hours            7346
5-6 hours            6183
More than 8 hours    6044
Others                 18
Name: count, dtype: int64

In [36]:
data['Sleep Duration'].unique()

<StringArray>
['5-6 hours', 'Less than 5 hours', '7-8 hours', 'More than 8 hours', 'Others']
Length: 5, dtype: str

## Adding Columns

In [41]:
data['Name']='Vikas Kumar'

In [43]:
data.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,...,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression,New_columns,New_column,Name
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,...,Healthy,B.Pharm,Yes,3.0,1.0,No,1,Saclar Value,Saclar Value,Vikas Kumar
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,...,Moderate,BSc,No,3.0,2.0,Yes,0,Saclar Value,Saclar Value,Vikas Kumar
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,...,Healthy,BA,No,9.0,1.0,Yes,0,Saclar Value,Saclar Value,Vikas Kumar
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,...,Moderate,BCA,Yes,4.0,5.0,Yes,1,Saclar Value,Saclar Value,Vikas Kumar
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,...,Moderate,M.Tech,Yes,1.0,1.0,No,0,Saclar Value,Saclar Value,Vikas Kumar

In [46]:
data['Bio'] = data['Age'].astype(str) + " " + data['Gender']

In [47]:
data

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,...,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression,New_columns,New_column,Name,Bio
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,...,B.Pharm,Yes,3.0,1.0,No,1,Saclar Value,Saclar Value,Vikas Kumar,33.0 Male
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,...,BSc,No,3.0,2.0,Yes,0,Saclar Value,Saclar Value,Vikas Kumar,24.0 Female
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,...,BA,No,9.0,1.0,Yes,0,Saclar Value,Saclar Value,Vikas Kumar,31.0 Male
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,...,BCA,Yes,4.0,5.0,Yes,1,Saclar Value,Saclar Value,Vikas Kumar,28.0 Female
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,...,M.Tech,Yes,1.0,1.0,No,0,Saclar Value,Saclar Value,Vikas Kumar,25.0 Female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,...,Class 12,Yes,7.0,1.0,Yes,0,Saclar Value,Saclar Value,Vikas Kumar,27.0 Female
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,...,MSc,No,0.0,3.0,Yes,0,Saclar Value,Saclar Value,Vikas Kumar,27.0 Male
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,...,MD,No,12.0,2.0,No,0,Saclar Value,Saclar Value,Vikas Kumar,31.0 Male
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,...,Class 12,Yes,10.0,5.0,No,1,Saclar Value,Saclar Value,Vikas Kumar,18.0 Female
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,...,BCA,Yes,2.0,3.0,Yes,1,Saclar Value,Saclar Value,Vikas Kumar,27.0 Male

In [51]:
data.drop('Name')

KeyError: "['Name'] not found in axis"

In [52]:
data

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,...,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression,New_columns,New_column,Name,Bio
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,...,B.Pharm,Yes,3.0,1.0,No,1,Saclar Value,Saclar Value,Vikas Kumar,33.0 Male
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,...,BSc,No,3.0,2.0,Yes,0,Saclar Value,Saclar Value,Vikas Kumar,24.0 Female
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,...,BA,No,9.0,1.0,Yes,0,Saclar Value,Saclar Value,Vikas Kumar,31.0 Male
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,...,BCA,Yes,4.0,5.0,Yes,1,Saclar Value,Saclar Value,Vikas Kumar,28.0 Female
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,...,M.Tech,Yes,1.0,1.0,No,0,Saclar Value,Saclar Value,Vikas Kumar,25.0 Female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,...,Class 12,Yes,7.0,1.0,Yes,0,Saclar Value,Saclar Value,Vikas Kumar,27.0 Female
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,...,MSc,No,0.0,3.0,Yes,0,Saclar Value,Saclar Value,Vikas Kumar,27.0 Male
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,...,MD,No,12.0,2.0,No,0,Saclar Value,Saclar Value,Vikas Kumar,31.0 Male
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,...,Class 12,Yes,10.0,5.0,No,1,Saclar Value,Saclar Value,Vikas Kumar,18.0 Female
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,...,BCA,Yes,2.0,3.0,Yes,1,Saclar Value,Saclar Value,Vikas Kumar,27.0 Male

In [53]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 22 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  str
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27898 non-null  float64
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
 18  New_columns                            27901 non-null  str
 19  New_column                             27901 non-null  str
 20  Name                                   27901 non-null  str
 21  Bio                                    27901 non-null  str
dtypes: float64(8), int64(2), str(12)
memory usage: 4.7 MB

In [54]:
data.drop(columns=['Name'], inplace=True)

In [55]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 21 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  str
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27898 non-null  float64
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
 18  New_columns                            27901 non-null  str
 19  New_column                             27901 non-null  str
 20  Bio                                    27901 non-null  str
dtypes: float64(8), int64(2), str(11)
memory usage: 4.5 MB